RATING_MATRIX_ITEM_ID_COL = "itemId"
RATING_MATRIX_USER_ID_COL = "userId"

ASSOCIATION_RULE_USER_COL = RATING_MATRIX_USER_ID_COL
ASSOCIATION_RULE_CONSEQUENTS_COL = "consequents"
ASSOCIATION_RULE_ANTECEDENTS_COL = "antecedents"
ASSOCIATION_RULE_COLUMNS = [ASSOCIATION_RULE_CONSEQUENTS_COL, ASSOCIATION_RULE_ANTECEDENTS_COL]
ASSOCIATION_RULE_COL_RENAME_MAP = {
    "consequents": RATING_MATRIX_ITEM_ID_COL,
    "row_number": "rank"}





